[package]
name = "arch-chromium"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[features]
default = []
cef-runtime = ["dep:cef"]

[dependencies]
cef = { workspace = true, optional = true }
thiserror.workspace = true
url.workspace = true

[lints]
workspace = true
