[package]
name = "archetype-protocol"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
archetype-types = { path = "../archetype-types" }
arch-paint = { path = "../arch-paint" }
base64.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true

[lints]
workspace = true
