[package]
name = "arch-paint"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
arch-layout = { path = "../arch-layout" }
arch-style = { path = "../arch-style" }
serde.workspace = true

[dev-dependencies]
arch-dom = { path = "../arch-dom" }

[lints]
workspace = true
