[package]
name = "archetype-sdk"
version = "0.1.0"
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[features]
internal-runtime-client = []

[dependencies]
arch-paint = { path = "../arch-paint" }
archetype-raster = { path = "../archetype-raster" }
archetype-protocol = { path = "../archetype-protocol" }
archetype-types = { path = "../archetype-types" }
getrandom.workspace = true
image.workspace = true
sha2.workspace = true
thiserror.workspace = true
url.workspace = true

[lints]
workspace = true

[dev-dependencies]
futures-executor.workspace = true
