name: Fuzz

on:
  push:
  pull_request:

jobs:
  parser-fuzz:
    runs-on: macos-14
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
        with:
          targets: x86_64-apple-darwin
      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-fuzz
      - run: cargo +nightly fuzz run html -- -max_total_time=20 -timeout=5
      - run: cargo +nightly fuzz run css -- -max_total_time=20 -timeout=5
